name: CI/CD QA Automation

permissions:
    content: read

# 1. El Disparador (Cuándo correr)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # 2. El Entorno (Dónde correr)
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    # 3. Preparar el Backend (PHP y SQLite)
    - name: Configurar PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: sqlite3

    # 4. Preparar el Entorno de QA (Python) con Caché
    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' #  Guarda en caché pytest, playwright y requests

    - name: Instalar librerías de Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Recuperar caché del navegador Chromium
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-chromium

    - name: Descargar Chromium (Solo la primera vez)
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: playwright install chromium --with-deps

    - name: Instalar dependencias del sistema operativo (Rápido)
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: playwright install-deps chromium
      
    # 5. Levantar la aplicación
    - name: Iniciar servidor PHP en segundo plano
      run: php -S localhost:8000 &
      
    - name: Esperar a que el servidor responda
      run: sleep 3

    # 6. Ejecutar la suite de pruebas
    - name: Correr tests con Pytest
      run: pytest tests/ -v
